services:
  - name: django-asgi-app
    type: web
    env: python
    buildCommand: "./build.sh"
    startCommand: "daphne -b 0.0.0.0 -p $PORT north_assignment.asgi:application"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: your-db
          property: connectionString
